name: ci

on:
  - push
  - pull_request

jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.29
        working-directory: ./pkg
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Setup Go version ${{ matrix.go }}
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.1
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build native
        run: |
          make build test
      - name: Build container
        run: |
          make container container-test
